server:
  port: 8081

spring:
  application:
    name: task-manager
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://localhost:5433/task-manager-db
    username: root
    password: 1234
#    url: ${DATABASE_URL}
#    username: ${DATABASE_USERNAME}
#    password: ${DATABASE_PASSWORD}